"""Initial migration.

Revision ID: 2ab6429aaf0a
Revises: 
Create Date: 2022-11-15 15:57:12.453168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab6429aaf0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aula', sa.String(length=20), nullable=True),
    sa.Column('horaEntrada', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('idAula', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idAula'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('id', 'nombre', 'apellido', 'idAula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumno')
    op.drop_table('salon')
    # ### end Alembic commands ###
